"""Автоматический загрузчик темы Power для всех Python скриптов"""

import sys
import site
from pathlib import Path

# Путь к файлу темы
THEME_PATH = Path(__file__).parent / 'power_theme.py'


# Создаём .pth файл для автозагрузки
def install_theme():
    """Установить тему глобально для всех Python скриптов"""
print(f"❤️‍🔥 Power Theme installing...")
# Содержимое для sitecustomize.py
sitecustomize_content = f"""
# Auto-generated by Power Theme installer
import sys
sys.path.insert(0, r'{THEME_PATH.parent}')

try:
    from power_theme import init_power_theme, console
    # Делаем доступным глобально
    import builtins
    builtins.console = console
    builtins.rprint = console.print
except ImportError:
    pass  # Тема не найдена, используем стандартный вывод
"""

# Находим site-packages
site_packages = site.getsitepackages()[0]
sitecustomize_path = Path(site_packages) / 'sitecustomize.py'

    # Сохраняем
sitecustomize_path.write_text(sitecustomize_content)
print(f"✅ Power Theme installed to {sitecustomize_path}")


if __name__ == "__main__":
    install_theme()